import Image from 'next/image'
import Header from "../components/Header";
import Footer from "../components/Footer";
import Blogcard from "../components/Blogcard";
import Blogcards from "../components/Blogcards";
import { Suspense } from "react";
import Head from "next/head";

export const metadata = {
  title: "New Next Project",
  description: "Generated by create next app",
};

async function getData() {
  const res = await fetch("https://www.carlelo.com/api/upcoming-cars-by-month");

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}
export default async function Home() {
  const names = ['Ada Lovelace', 'Grace Hopper', 'Margaret Hamilton'];
  const jsonLd = [
    {
      "@context": "http://schema.org",
      "@type": "WebPage",
      name: "Create Next App",
      description: "Generated by create next app",
    },
    {
      "@context": "https://schema.org",
      "@type": "ViewAction",
      target: [
        {
          "@type": "EntryPoint",
          urlTemplate: "https://www.carlelo.com/jeep-cars/jeepster",
        },
      ],
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "What are the alternatives/competitors of the upcoming Jeep Jeepster?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "<p>The upcoming Jeep Jeepster will go up against the Tata Punch, Citroen C3 and others in its segment.</p>",
          },
        },
        {
          "@type": "Question",
          name: "What are the expected key specifications of the upcoming Jeep Jeepster?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "<p>The Jeep Jeepster is a sub-compact SUV that will underpin the brand&rsquo;s eCMP modular platform. The four-wheeler is expected to come equipped with a segment first e-All Wheel Drive (eAWD) system.</p>",
          },
        },
        {
          "@type": "Question",
          name: "What is the expected price of the upcoming Jeep Jeepster?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "<p>The price of the upcoming Jeep Jeepster is expected to start from Rs 10 lakh (ex-showroom).</p>",
          },
        },
        {
          "@type": "Question",
          name: "What is the estimated launch date of the upcoming Jeep Jeepster?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "<p>The estimated launch date of the upcoming Jeep Jeepster is set around March 2023.</p>",
          },
        },
      ],
    },
  ];
  const data = await getData();
  const main_data = data;
  return (
    <>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Header />
      <Suspense fallback={<p>Loading feed...</p>}>
        <h2 className="text-center m-4">Upcoming Cars</h2>
        <div className="row ">
          {main_data.map((value: { id: any; }) => {
            return <Blogcard  key={value.id} {...value} />
          })}
        </div>
        
      </Suspense>

      <Footer />
    </>
  )
}
